In [1]:
import os
os.environ['DJANGO_ALLOW_ASYNC_UNSAFE'] = 'true'

In [2]:
# untuk import export
from tablib import Dataset
import pandas as pd
import numpy as np

# # sklearn package / module
from sklearn import linear_model
from sklearn import preprocessing
from sklearn.naive_bayes import GaussianNB
from sklearn import metrics
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.model_selection import train_test_split

from mixed_naive_bayes import MixedNB

from myapp.models import Datas
from pydataset import data

In [3]:
db = Datas.objects.all()
df = pd.DataFrame(db.values())
csv = df.copy()

In [4]:
label_encoder = preprocessing.LabelEncoder()

In [5]:
df

,id,nama_siswa,jenis_kelamin,tinggi_badan,berat_badan,kemampuan_fisik,teknik_dasar,hasil_bakat
0,1054,Abdul Rahman,laki_laki,145,35,66,67,tidak berbakat
1,1055,Alisia Destiani,perempuan,145,38,68,70,tidak berbakat
2,1056,Aspian,laki_laki,148,42,85,80,berbakat
3,1057,Asrida,perempuan,145,33,77,79,tidak berbakat
4,1058,Fauzia,laki_laki,150,40,96,98,berbakat
5,1059,Fendi,laki_laki,148,39,65,70,tidak berbakat
6,1060,Ficar,laki_laki,147,40,64,68,tidak berbakat
7,1061,Fikram,laki_laki,148,45,65,68,tidak berbakat
8,1062,Firdaus Zahardin Ambu,laki_laki,150,45,84,85,berbakat
9,1063,Helmina,perempuan,145,42,82,80,berbakat
10,1064,Ian Ardiansa,laki_laki,146,38,75,75,tidak berbakat
11,1065,Ilham,laki_laki,148,36,65,67,tidak berbakat
12,1066,La Ode Abdul Zaki,laki_laki,145,36,64,66,tidak berbakat
13,1067,Lastri Mariska,perempuan,142,33,64,66,tidak berbakat
14,1068,Muh. Farhan Uma Waitina,laki_laki,146,39,75,78,tidak berbakat
15,1069,Muhamad Aldi,laki_laki,147,37,65,70,tidak berbakat
16,1070,Muhammad Zaki,laki_laki,148,40,80,85,berbakat
17,1071,Musdin,laki_laki,149,38,65,66,tidak berbakat
18,1072,Nilam Syakila,perempuan,146,37,85,88,berbakat
19,1073,Ray Azura,perempuan,146,39,84,84,berbakat
20,1074,Restu Rahma Dewi Salam,perempuan,145,40,88,85,berbakat
21,1075,Reylan Aprianto,laki_laki,147,39,86,90,berbakat
22,1076,Riswan,laki_laki,149,37,75,75,tidak berbakat
23,1077,Safina,perempuan,146,38,98,99,berbakat
24,1078,Salmatia,perempuan,145,35,74,75,tidak berbakat
25,1079,Sarmila,perempuan,146,37,95,97,berbakat
26,1080,Sawaludin,laki_laki,149,37,75,78,tidak berbakat
27,1081,Sukri,laki_laki,148,40,80,80,berbakat
28,1082,Yusna,perempuan,150,39,90,95,berbakat
29,1083,Aditya,laki_laki,152,48,88,90,berbakat
30,1084,Afdal Ali,laki_laki,147,39,78,75,tidak berbakat
31,1085,Aldi Wali,laki_laki,156,38,79,72,tidak berbakat
32,1086,Andrian Setyawan,laki_laki,150,45,85,88,berbakat
33,1087,Aril Prasetyo,laki_laki,149,45,83,80,berbakat
34,1088,Canda Alivia,perempuan,146,35,70,76,tidak berbakat
35,1089,Desti Rahmasia Sarifudin,perempuan,148,42,80,82,berbakat
36,1090,Fadila,perempuan,144,37,70,70,tidak berbakat
37,1091,Iski Dayanti,perempuan,145,34,72,70,tidak berbakat
38,1092,Jufriyadin,laki_laki,146,35,74,72,tidak berbakat
39,1093,Junardin,laki_laki,149,37,79,75,tidak berbakat
40,1094,Junaydin,laki_laki,146,36,75,77,tidak berbakat
41,1095,La Ode Jufrianto,laki_laki,150,48,74,74,tidak berbakat
42,1096,La Ode Sigit Munandar,laki_laki,152,44,88,90,berbakat
43,1097,Lilis,perempuan,142,34,76,73,tidak berbakat
44,1098,Muhamad Syahril,laki_laki,156,45,85,89,berbakat
45,1099,Munaesi Biloro,perempuan,145,34,70,71,tidak berbakat
46,1100,Mutiyah Zaliyanti,perempuan,146,35,78,76,tidak berbakat
47,1101,Rahma Arifqa,perempuan,148,40,85,88,berbakat
48,1102,Rifail Halim,laki_laki,144,36,77,74,tidak berbakat
49,1103,Rifaldi,laki_laki,142,35,72,72,tidak berbakat
50,1104,Sadam,laki_laki,145,37,74,70,tidak berbakat
51,1105,Said,laki_laki,147,42,90,90,berbakat
52,1106,Selfianti,perempuan,145,35,76,73,tidak berbakat
53,1107,Suci Yanti,perempuan,148,40,83,86,berbakat
54,1108,Sukmayanti,perempuan,150,45,89,85,berbakat
55,1109,Sulastri,perempuan,145,34,76,76,tidak berbakat
56,1110,Titin Indrayani,perempuan,147,35,77,75,tidak berbakat
57,1111,Tri Fadila,perempuan,142,33,76,78,tidak berbakat
58,1112,Wa Ode Yolan Sari,perempuan,150,40,80,82,berbakat
59,1113,Risman,laki_laki,149,37,78,75,tidak berbakat
60,1114,Andini,perempuan,144,34,73,72,tidak berbakat
61,1115,Andre Anggriawan,laki_laki,152,48,74,72,tidak berbakat
62,1116,Dea Purwandini,perempuan,148,39,88,90,berbakat
63,1117,Elsi Aprilia,perempuan,146,38,74,72,tidak berbakat
64,1118,Erlangga,laki_laki,149,40,80,82,berbakat
65,1119,Fahril Anton,laki_laki,150,45,92,89,berbakat
66,1120,Fardina Idris,laki_laki,145,35,78,75,tidak berbakat
67,1121,Ifan Kamali,laki_laki,155,40,75,75,tidak berbakat
68,1122,Intan Marlia,perempuan,148,35,85,85,berbakat
69,1123,Irsan,laki_laki,156,37,86,88,berbakat
70,1124,Israwati,perempuan,142,35,72,76,tidak berbakat
71,1125,La Ode Sofyan,laki_laki,145,36,70,72,tidak berbakat
72,1126,Ld. Muhamad Afat Harlin,laki_laki,145,35,76,78,tidak berbakat
73,1127,Naldianto,laki_laki,149,38,75,74,tidak berbakat
74,1128,Nesti Soviana,perempuan,152,40,90,88,berbakat
75,1129,Nurmila,perempuan,146,38,86,88,berbakat
76,1130,Ratina,perempuan,147,35,75,74,tidak berbakat
77,1131,Rusbardin,laki_laki,148,38,79,74,tidak berbakat
78,1132,Selis,perempuan,145,34,74,76,tidak berbakat
79,1133,Selvi Safira,perempuan,149,39,76,77,tidak berbakat
80,1134,Siti Dwi Nurain,perempuan,150,44,90,89,berbakat
81,1135,Tirta,laki_laki,148,42,86,82,berbakat
82,1136,Wa Ode Astrid Amrin,perempuan,150,40,88,88,berbakat
83,1137,Yuslan,laki_laki,149,40,81,83,berbakat
84,1138,Cecep Ardiasyah,laki_laki,146,38,73,72,tidak berbakat
85,1139,Janet Alhanur,perempuan,143,32,75,73,tidak berbakat
86,1140,Ahmad Saiful Sudiarto,laki_laki,144,34,77,74,tidak berbakat
87,1141,Friska,perempuan,144,34,76,78,tidak berbakat
88,1142,Alfauzi,laki_laki,146,35,76,74,tidak berbakat
89,1143,Andri,laki_laki,149,38,73,70,tidak berbakat
90,1144,Arman,laki_laki,145,48,88,85,berbakat
91,1145,Delsiana,perempuan,145,35,77,73,tidak berbakat
92,1146,Desi,perempuan,144,35,85,82,berbakat
93,1147,Eli Safitri,perempuan,146,38,72,70,tidak berbakat
94,1148,Etika,perempuan,146,34,76,74,tidak berbakat
95,1149,Ezzilia Dewi,perempuan,147,39,85,84,berbakat
96,1150,Fahril Basri,laki_laki,147,45,88,85,berbakat
97,1151,Halim,laki_laki,150,42,76,78,tidak berbakat
98,1152,Imran,laki_laki,149,45,92,90,berbakat
99,1153,Ira,perempuan,148,39,74,75,tidak berbakat
100,1154,La Wahid,laki_laki,155,45,95,90,berbakat
101,1155,Lasri,perempuan,144,34,73,75,tidak berbakat
102,1156,Muh. Faras Ramadan,laki_laki,148,38,75,72,tidak berbakat
103,1157,Muhamad Galang Ardana,laki_laki,150,40,70,70,tidak berbakat
104,1158,Nestianti,perempuan,145,35,77,75,tidak berbakat
105,1159,Nurfadila,perempuan,144,32,74,74,tidak berbakat
106,1160,Risni Karmini,perempuan,143,33,70,70,tidak berbakat
107,1161,Safaat,laki_laki,149,45,90,90,berbakat
108,1162,Sahlan Arafa,laki_laki,148,44,92,94,berbakat
109,1163,Sri Iriyanti,perempuan,140,34,75,78,tidak berbakat
110,1164,Vita,perempuan,144,32,75,72,tidak berbakat
111,1165,Wa Ode Hasti,perempuan,145,36,76,74,tidak berbakat
112,1166,Wd. Lusi Artika Tima,perempuan,150,38,82,80,berbakat
113,1167,Rido Femia,laki_laki,148,40,77,74,tidak berbakat
114,1168,Zackfhian Syahfitra,laki_laki,156,48,88,88,berbakat
115,1169,Rezky Yudiansyah Pratama,laki_laki,154,45,86,88,berbakat

In [6]:
csv[['jenis_kelamin']] = np.where(csv[['jenis_kelamin']] == 'perempuan', 0, 1)
csv[['hasil_bakat']] = np.where(csv[['hasil_bakat']] == 'berbakat', 1, 0)
# csv[['hasil_bakat']] = csv[['hasil_bakat']].apply(label_encoder.fit_transform)
csv[['kemampuan_fisik', 'teknik_dasar']] = np.where(csv[['kemampuan_fisik', 'teknik_dasar']] < 80.0, 0, 1)

In [7]:
csv

,id,nama_siswa,jenis_kelamin,tinggi_badan,berat_badan,kemampuan_fisik,teknik_dasar,hasil_bakat
0,1054,Abdul Rahman,1,145,35,0,0,0
1,1055,Alisia Destiani,0,145,38,0,0,0
2,1056,Aspian,1,148,42,1,1,1
3,1057,Asrida,0,145,33,0,0,0
4,1058,Fauzia,1,150,40,1,1,1
5,1059,Fendi,1,148,39,0,0,0
6,1060,Ficar,1,147,40,0,0,0
7,1061,Fikram,1,148,45,0,0,0
8,1062,Firdaus Zahardin Ambu,1,150,45,1,1,1
9,1063,Helmina,0,145,42,1,1,1
10,1064,Ian Ardiansa,1,146,38,0,0,0
11,1065,Ilham,1,148,36,0,0,0
12,1066,La Ode Abdul Zaki,1,145,36,0,0,0
13,1067,Lastri Mariska,0,142,33,0,0,0
14,1068,Muh. Farhan Uma Waitina,1,146,39,0,0,0
15,1069,Muhamad Aldi,1,147,37,0,0,0
16,1070,Muhammad Zaki,1,148,40,1,1,1
17,1071,Musdin,1,149,38,0,0,0
18,1072,Nilam Syakila,0,146,37,1,1,1
19,1073,Ray Azura,0,146,39,1,1,1
20,1074,Restu Rahma Dewi Salam,0,145,40,1,1,1
21,1075,Reylan Aprianto,1,147,39,1,1,1
22,1076,Riswan,1,149,37,0,0,0
23,1077,Safina,0,146,38,1,1,1
24,1078,Salmatia,0,145,35,0,0,0
25,1079,Sarmila,0,146,37,1,1,1
26,1080,Sawaludin,1,149,37,0,0,0
27,1081,Sukri,1,148,40,1,1,1
28,1082,Yusna,0,150,39,1,1,1
29,1083,Aditya,1,152,48,1,1,1
30,1084,Afdal Ali,1,147,39,0,0,0
31,1085,Aldi Wali,1,156,38,0,0,0
32,1086,Andrian Setyawan,1,150,45,1,1,1
33,1087,Aril Prasetyo,1,149,45,1,1,1
34,1088,Canda Alivia,0,146,35,0,0,0
35,1089,Desti Rahmasia Sarifudin,0,148,42,1,1,1
36,1090,Fadila,0,144,37,0,0,0
37,1091,Iski Dayanti,0,145,34,0,0,0
38,1092,Jufriyadin,1,146,35,0,0,0
39,1093,Junardin,1,149,37,0,0,0
40,1094,Junaydin,1,146,36,0,0,0
41,1095,La Ode Jufrianto,1,150,48,0,0,0
42,1096,La Ode Sigit Munandar,1,152,44,1,1,1
43,1097,Lilis,0,142,34,0,0,0
44,1098,Muhamad Syahril,1,156,45,1,1,1
45,1099,Munaesi Biloro,0,145,34,0,0,0
46,1100,Mutiyah Zaliyanti,0,146,35,0,0,0
47,1101,Rahma Arifqa,0,148,40,1,1,1
48,1102,Rifail Halim,1,144,36,0,0,0
49,1103,Rifaldi,1,142,35,0,0,0
50,1104,Sadam,1,145,37,0,0,0
51,1105,Said,1,147,42,1,1,1
52,1106,Selfianti,0,145,35,0,0,0
53,1107,Suci Yanti,0,148,40,1,1,1
54,1108,Sukmayanti,0,150,45,1,1,1
55,1109,Sulastri,0,145,34,0,0,0
56,1110,Titin Indrayani,0,147,35,0,0,0
57,1111,Tri Fadila,0,142,33,0,0,0
58,1112,Wa Ode Yolan Sari,0,150,40,1,1,1
59,1113,Risman,1,149,37,0,0,0
60,1114,Andini,0,144,34,0,0,0
61,1115,Andre Anggriawan,1,152,48,0,0,0
62,1116,Dea Purwandini,0,148,39,1,1,0
63,1117,Elsi Aprilia,0,146,38,0,0,0
64,1118,Erlangga,1,149,40,1,1,1
65,1119,Fahril Anton,1,150,45,1,1,1
66,1120,Fardina Idris,1,145,35,0,0,0
67,1121,Ifan Kamali,1,155,40,0,0,0
68,1122,Intan Marlia,0,148,35,1,1,1
69,1123,Irsan,1,156,37,1,1,1
70,1124,Israwati,0,142,35,0,0,0
71,1125,La Ode Sofyan,1,145,36,0,0,0
72,1126,Ld. Muhamad Afat Harlin,1,145,35,0,0,0
73,1127,Naldianto,1,149,38,0,0,0
74,1128,Nesti Soviana,0,152,40,1,1,1
75,1129,Nurmila,0,146,38,1,1,1
76,1130,Ratina,0,147,35,0,0,0
77,1131,Rusbardin,1,148,38,0,0,0
78,1132,Selis,0,145,34,0,0,0
79,1133,Selvi Safira,0,149,39,0,0,0
80,1134,Siti Dwi Nurain,0,150,44,1,1,1
81,1135,Tirta,1,148,42,1,1,1
82,1136,Wa Ode Astrid Amrin,0,150,40,1,1,1
83,1137,Yuslan,1,149,40,1,1,1
84,1138,Cecep Ardiasyah,1,146,38,0,0,0
85,1139,Janet Alhanur,0,143,32,0,0,0
86,1140,Ahmad Saiful Sudiarto,1,144,34,0,0,0
87,1141,Friska,0,144,34,0,0,0
88,1142,Alfauzi,1,146,35,0,0,0
89,1143,Andri,1,149,38,0,0,0
90,1144,Arman,1,145,48,1,1,1
91,1145,Delsiana,0,145,35,0,0,0
92,1146,Desi,0,144,35,1,1,1
93,1147,Eli Safitri,0,146,38,0,0,0
94,1148,Etika,0,146,34,0,0,0
95,1149,Ezzilia Dewi,0,147,39,1,1,1
96,1150,Fahril Basri,1,147,45,1,1,1
97,1151,Halim,1,150,42,0,0,0
98,1152,Imran,1,149,45,1,1,1
99,1153,Ira,0,148,39,0,0,0
100,1154,La Wahid,1,155,45,1,1,1
101,1155,Lasri,0,144,34,0,0,0
102,1156,Muh. Faras Ramadan,1,148,38,0,0,0
103,1157,Muhamad Galang Ardana,1,150,40,0,0,0
104,1158,Nestianti,0,145,35,0,0,0
105,1159,Nurfadila,0,144,32,0,0,0
106,1160,Risni Karmini,0,143,33,0,0,0
107,1161,Safaat,1,149,45,1,1,1
108,1162,Sahlan Arafa,1,148,44,1,1,1
109,1163,Sri Iriyanti,0,140,34,0,0,0
110,1164,Vita,0,144,32,0,0,0
111,1165,Wa Ode Hasti,0,145,36,0,0,0
112,1166,Wd. Lusi Artika Tima,0,150,38,1,1,1
113,1167,Rido Femia,1,148,40,0,0,0
114,1168,Zackfhian Syahfitra,1,156,48,1,1,1
115,1169,Rezky Yudiansyah Pratama,1,154,45,1,1,1

In [8]:
kondisi = [
		(csv['jenis_kelamin'] == 1) & (csv['tinggi_badan'] < 148),
		(csv['jenis_kelamin'] == 1) & (csv['tinggi_badan'] > 158),
		(csv['jenis_kelamin'] == 0) & (csv['tinggi_badan'] < 145), 
		(csv['jenis_kelamin'] == 0) & (csv['tinggi_badan'] > 155)
	]

In [11]:
kondisi_berat_badan = [
		(csv['jenis_kelamin'] == 1) & (csv['berat_badan'] < 37),
		(csv['jenis_kelamin'] == 1) & (csv['berat_badan'] > 45),
		(csv['jenis_kelamin'] == 0) & (csv['berat_badan'] < 35), 
		(csv['jenis_kelamin'] == 0) & (csv['berat_badan'] > 40)
	]

In [12]:
pilihan = [0, 0, 0, 0]

In [13]:
csv['tinggi_badan'] = np.select(kondisi, pilihan, default=1)
csv['berat_badan'] = np.select(kondisi_berat_badan, pilihan, default=1)

In [14]:
csv

,id,nama_siswa,jenis_kelamin,tinggi_badan,berat_badan,kemampuan_fisik,teknik_dasar,hasil_bakat
0,1054,Abdul Rahman,1,0,0,0,0,0
1,1055,Alisia Destiani,0,1,1,0,0,0
2,1056,Aspian,1,1,1,1,1,1
3,1057,Asrida,0,1,0,0,0,0
4,1058,Fauzia,1,1,1,1,1,1
5,1059,Fendi,1,1,1,0,0,0
6,1060,Ficar,1,0,1,0,0,0
7,1061,Fikram,1,1,1,0,0,0
8,1062,Firdaus Zahardin Ambu,1,1,1,1,1,1
9,1063,Helmina,0,1,0,1,1,1
10,1064,Ian Ardiansa,1,0,1,0,0,0
11,1065,Ilham,1,1,0,0,0,0
12,1066,La Ode Abdul Zaki,1,0,0,0,0,0
13,1067,Lastri Mariska,0,0,0,0,0,0
14,1068,Muh. Farhan Uma Waitina,1,0,1,0,0,0
15,1069,Muhamad Aldi,1,0,1,0,0,0
16,1070,Muhammad Zaki,1,1,1,1,1,1
17,1071,Musdin,1,1,1,0,0,0
18,1072,Nilam Syakila,0,1,1,1,1,1
19,1073,Ray Azura,0,1,1,1,1,1
20,1074,Restu Rahma Dewi Salam,0,1,1,1,1,1
21,1075,Reylan Aprianto,1,0,1,1,1,1
22,1076,Riswan,1,1,1,0,0,0
23,1077,Safina,0,1,1,1,1,1
24,1078,Salmatia,0,1,1,0,0,0
25,1079,Sarmila,0,1,1,1,1,1
26,1080,Sawaludin,1,1,1,0,0,0
27,1081,Sukri,1,1,1,1,1,1
28,1082,Yusna,0,1,1,1,1,1
29,1083,Aditya,1,1,0,1,1,1
30,1084,Afdal Ali,1,0,1,0,0,0
31,1085,Aldi Wali,1,1,1,0,0,0
32,1086,Andrian Setyawan,1,1,1,1,1,1
33,1087,Aril Prasetyo,1,1,1,1,1,1
34,1088,Canda Alivia,0,1,1,0,0,0
35,1089,Desti Rahmasia Sarifudin,0,1,0,1,1,1
36,1090,Fadila,0,0,1,0,0,0
37,1091,Iski Dayanti,0,1,0,0,0,0
38,1092,Jufriyadin,1,0,0,0,0,0
39,1093,Junardin,1,1,1,0,0,0
40,1094,Junaydin,1,0,0,0,0,0
41,1095,La Ode Jufrianto,1,1,0,0,0,0
42,1096,La Ode Sigit Munandar,1,1,1,1,1,1
43,1097,Lilis,0,0,0,0,0,0
44,1098,Muhamad Syahril,1,1,1,1,1,1
45,1099,Munaesi Biloro,0,1,0,0,0,0
46,1100,Mutiyah Zaliyanti,0,1,1,0,0,0
47,1101,Rahma Arifqa,0,1,1,1,1,1
48,1102,Rifail Halim,1,0,0,0,0,0
49,1103,Rifaldi,1,0,0,0,0,0
50,1104,Sadam,1,0,1,0,0,0
51,1105,Said,1,0,1,1,1,1
52,1106,Selfianti,0,1,1,0,0,0
53,1107,Suci Yanti,0,1,1,1,1,1
54,1108,Sukmayanti,0,1,0,1,1,1
55,1109,Sulastri,0,1,0,0,0,0
56,1110,Titin Indrayani,0,1,1,0,0,0
57,1111,Tri Fadila,0,0,0,0,0,0
58,1112,Wa Ode Yolan Sari,0,1,1,1,1,1
59,1113,Risman,1,1,1,0,0,0
60,1114,Andini,0,0,0,0,0,0
61,1115,Andre Anggriawan,1,1,0,0,0,0
62,1116,Dea Purwandini,0,1,1,1,1,0
63,1117,Elsi Aprilia,0,1,1,0,0,0
64,1118,Erlangga,1,1,1,1,1,1
65,1119,Fahril Anton,1,1,1,1,1,1
66,1120,Fardina Idris,1,0,0,0,0,0
67,1121,Ifan Kamali,1,1,1,0,0,0
68,1122,Intan Marlia,0,1,1,1,1,1
69,1123,Irsan,1,1,1,1,1,1
70,1124,Israwati,0,0,1,0,0,0
71,1125,La Ode Sofyan,1,0,0,0,0,0
72,1126,Ld. Muhamad Afat Harlin,1,0,0,0,0,0
73,1127,Naldianto,1,1,1,0,0,0
74,1128,Nesti Soviana,0,1,1,1,1,1
75,1129,Nurmila,0,1,1,1,1,1
76,1130,Ratina,0,1,1,0,0,0
77,1131,Rusbardin,1,1,1,0,0,0
78,1132,Selis,0,1,0,0,0,0
79,1133,Selvi Safira,0,1,1,0,0,0
80,1134,Siti Dwi Nurain,0,1,0,1,1,1
81,1135,Tirta,1,1,1,1,1,1
82,1136,Wa Ode Astrid Amrin,0,1,1,1,1,1
83,1137,Yuslan,1,1,1,1,1,1
84,1138,Cecep Ardiasyah,1,0,1,0,0,0
85,1139,Janet Alhanur,0,0,0,0,0,0
86,1140,Ahmad Saiful Sudiarto,1,0,0,0,0,0
87,1141,Friska,0,0,0,0,0,0
88,1142,Alfauzi,1,0,0,0,0,0
89,1143,Andri,1,1,1,0,0,0
90,1144,Arman,1,0,0,1,1,1
91,1145,Delsiana,0,1,1,0,0,0
92,1146,Desi,0,0,1,1,1,1
93,1147,Eli Safitri,0,1,1,0,0,0
94,1148,Etika,0,1,0,0,0,0
95,1149,Ezzilia Dewi,0,1,1,1,1,1
96,1150,Fahril Basri,1,0,1,1,1,1
97,1151,Halim,1,1,1,0,0,0
98,1152,Imran,1,1,1,1,1,1
99,1153,Ira,0,1,1,0,0,0
100,1154,La Wahid,1,1,1,1,1,1
101,1155,Lasri,0,0,0,0,0,0
102,1156,Muh. Faras Ramadan,1,1,1,0,0,0
103,1157,Muhamad Galang Ardana,1,1,1,0,0,0
104,1158,Nestianti,0,1,1,0,0,0
105,1159,Nurfadila,0,0,0,0,0,0
106,1160,Risni Karmini,0,0,0,0,0,0
107,1161,Safaat,1,1,1,1,1,1
108,1162,Sahlan Arafa,1,1,1,1,1,1
109,1163,Sri Iriyanti,0,0,0,0,0,0
110,1164,Vita,0,0,0,0,0,0
111,1165,Wa Ode Hasti,0,1,1,0,0,0
112,1166,Wd. Lusi Artika Tima,0,1,1,1,1,1
113,1167,Rido Femia,1,1,1,0,0,0
114,1168,Zackfhian Syahfitra,1,1,0,1,1,1
115,1169,Rezky Yudiansyah Pratama,1,1,1,1,1,1

# pembagian data

In [15]:
y = csv['hasil_bakat']	 # y_train

In [16]:
x = csv[['jenis_kelamin', 'tinggi_badan', 'berat_badan', 'kemampuan_fisik','teknik_dasar']]

# proses perhitungan algoritma naive bayes

In [17]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.3, random_state=0)

In [18]:
nv = GaussianNB()
ajar = nv.fit(x_train, y_train)
y_pred = nv.predict(x_test)

In [19]:

	# mixed
	data_y = pd.DataFrame(y)
	data_y = data_y.apply(label_encoder.fit_transform)
	yyy = data_y['hasil_bakat']
	clf = MixedNB(categorical_features=[0,1])       #discrete and continues data
	# clf = MixedNB(categorical_features='all')		# discrete data only
	# clf = MixedNB()									# continuous data only
	clf.fit(x,yyy)
	prediksi_mixed = clf.predict(x_test)
	encoder_y_test = label_encoder.transform(y_test)
	
	akurasi_mixed = accuracy_score(encoder_y_test, prediksi_mixed)

	# end mixed

[2 2]

In [20]:
gabung = x_train.copy()
gabung.insert(5,'hasil_bakat',y_train,True)
x_train_y_train = gabung.copy()

# kembalikan ke file awal (decoder)

In [21]:
gabung['jenis_kelamin'] = np.where(gabung['jenis_kelamin'] == 0, 'perempuan', 'laki-laki')

In [22]:
gabung['hasil_bakat'] = np.where(gabung['hasil_bakat'] == 1 , 'berbakat', 'tidak berbakat')

In [23]:
gabung

,jenis_kelamin,tinggi_badan,berat_badan,kemampuan_fisik,teknik_dasar,hasil_bakat
54,perempuan,1,0,1,1,berbakat
115,laki-laki,1,1,1,1,berbakat
95,perempuan,1,1,1,1,berbakat
101,perempuan,0,0,0,0,tidak berbakat
96,laki-laki,0,1,1,1,berbakat
91,perempuan,1,1,0,0,tidak berbakat
63,perempuan,1,1,0,0,tidak berbakat
27,laki-laki,1,1,1,1,berbakat
18,perempuan,1,1,1,1,berbakat
11,laki-laki,1,0,0,0,tidak berbakat
59,laki-laki,1,1,0,0,tidak berbakat
68,perempuan,1,1,1,1,berbakat
61,laki-laki,1,0,0,0,tidak berbakat
76,perempuan,1,1,0,0,tidak berbakat
50,laki-laki,0,1,0,0,tidak berbakat
1,perempuan,1,1,0,0,tidak berbakat
104,perempuan,1,1,0,0,tidak berbakat
42,laki-laki,1,1,1,1,berbakat
41,laki-laki,1,0,0,0,tidak berbakat
4,laki-laki,1,1,1,1,berbakat
15,laki-laki,0,1,0,0,tidak berbakat
17,laki-laki,1,1,0,0,tidak berbakat
52,perempuan,1,1,0,0,tidak berbakat
40,laki-laki,0,0,0,0,tidak berbakat
38,laki-laki,0,0,0,0,tidak berbakat
5,laki-laki,1,1,0,0,tidak berbakat
53,perempuan,1,1,1,1,berbakat
106,perempuan,0,0,0,0,tidak berbakat
108,laki-laki,1,1,1,1,berbakat
0,laki-laki,0,0,0,0,tidak berbakat
34,perempuan,1,1,0,0,tidak berbakat
28,perempuan,1,1,1,1,berbakat
55,perempuan,1,0,0,0,tidak berbakat
35,perempuan,1,0,1,1,berbakat
23,perempuan,1,1,1,1,berbakat
31,laki-laki,1,1,0,0,tidak berbakat
75,perempuan,1,1,1,1,berbakat
57,perempuan,0,0,0,0,tidak berbakat
89,laki-laki,1,1,0,0,tidak berbakat
99,perempuan,1,1,0,0,tidak berbakat
32,laki-laki,1,1,1,1,berbakat
98,laki-laki,1,1,1,1,berbakat
14,laki-laki,0,1,0,0,tidak berbakat
85,perempuan,0,0,0,0,tidak berbakat
19,perempuan,1,1,1,1,berbakat
29,laki-laki,1,0,1,1,berbakat
49,laki-laki,0,0,0,0,tidak berbakat
82,perempuan,1,1,1,1,berbakat
113,laki-laki,1,1,0,0,tidak berbakat
114,laki-laki,1,0,1,1,berbakat
79,perempuan,1,1,0,0,tidak berbakat
69,laki-laki,1,1,1,1,berbakat
80,perempuan,1,0,1,1,berbakat
20,perempuan,1,1,1,1,berbakat
109,perempuan,0,0,0,0,tidak berbakat
72,laki-laki,0,0,0,0,tidak berbakat
77,laki-laki,1,1,0,0,tidak berbakat
25,perempuan,1,1,1,1,berbakat
37,perempuan,1,0,0,0,tidak berbakat
81,laki-laki,1,1,1,1,berbakat
102,laki-laki,1,1,0,0,tidak berbakat
46,perempuan,1,1,0,0,tidak berbakat
105,perempuan,0,0,0,0,tidak berbakat
39,laki-laki,1,1,0,0,tidak berbakat
65,laki-laki,1,1,1,1,berbakat
58,perempuan,1,1,1,1,berbakat
12,laki-laki,0,0,0,0,tidak berbakat
110,perempuan,0,0,0,0,tidak berbakat
88,laki-laki,0,0,0,0,tidak berbakat
70,perempuan,0,1,0,0,tidak berbakat
87,perempuan,0,0,0,0,tidak berbakat
36,perempuan,0,1,0,0,tidak berbakat
21,laki-laki,0,1,1,1,berbakat
83,laki-laki,1,1,1,1,berbakat
9,perempuan,1,0,1,1,berbakat
103,laki-laki,1,1,0,0,tidak berbakat
112,perempuan,1,1,1,1,berbakat
67,laki-laki,1,1,0,0,tidak berbakat
64,laki-laki,1,1,1,1,berbakat
47,perempuan,1,1,1,1,berbakat
44,laki-laki,1,1,1,1,berbakat

In [24]:
kamusdata = {
		'jenis_kelamin'	: np.array([0]),
		'tinggi_badan'	: np.array([0]),
		'berat_badan'	: np.array([0]),
		'kemampuan_fisik'	: np.array([0]),
		'teknik_dasar'	: np.array([0]),
		'hasil_bakat'	: np.array([0]),
	}

In [26]:
kamusdata

{'jenis_kelamin': array([0]),
 'tinggi_badan': array([0]),
 'berat_badan': array([0]),
 'kemampuan_fisik': array([0]),
 'teknik_dasar': array([0]),
 'hasil_bakat': array([0])}

In [27]:
test = pd.DataFrame(kamusdata)
# prediksi_test = nv.predict(test)

In [28]:
test

,jenis_kelamin,tinggi_badan,berat_badan,kemampuan_fisik,teknik_dasar,hasil_bakat
0,0,0,0,0,0,0

In [29]:
test['jenis_kelamin'] = np.where(test['jenis_kelamin'] == 0, ' ', ' ')

In [30]:
test

,jenis_kelamin,tinggi_badan,berat_badan,kemampuan_fisik,teknik_dasar,hasil_bakat
0,,0,0,0,0,0

In [31]:
print(kamusdata)

{'jenis_kelamin': array([0]), 'tinggi_badan': array([0]), 'berat_badan': array([0]), 'kemampuan_fisik': array([0]), 'teknik_dasar': array([0]), 'hasil_bakat': array([0])}

In [32]:
	prediksi_post = ''

In [33]:
# test['jenis_kelamin'] = np.where(test['jenis_kelamin'] == 0, ' ', ' ')
# test[['ipk','ipk_prodi','ipk1','ipk2','ipk3','ipk4','ipk4','ipk5','ipk6','sam_bekerja','p_mengulang', 'p_cuti', 'a_papua']] = np.where(test[['ipk','ipk_prodi','ipk1','ipk2','ipk3','ipk4','ipk4','ipk5','ipk6','sam_bekerja','p_mengulang', 'p_cuti', 'a_papua']] == 0, ' ', ' ')	# 2 kondisi ya/tidak

In [35]:
gabung

,jenis_kelamin,tinggi_badan,berat_badan,kemampuan_fisik,teknik_dasar,hasil_bakat
54,perempuan,1,0,1,1,berbakat
115,laki-laki,1,1,1,1,berbakat
95,perempuan,1,1,1,1,berbakat
101,perempuan,0,0,0,0,tidak berbakat
96,laki-laki,0,1,1,1,berbakat
91,perempuan,1,1,0,0,tidak berbakat
63,perempuan,1,1,0,0,tidak berbakat
27,laki-laki,1,1,1,1,berbakat
18,perempuan,1,1,1,1,berbakat
11,laki-laki,1,0,0,0,tidak berbakat
59,laki-laki,1,1,0,0,tidak berbakat
68,perempuan,1,1,1,1,berbakat
61,laki-laki,1,0,0,0,tidak berbakat
76,perempuan,1,1,0,0,tidak berbakat
50,laki-laki,0,1,0,0,tidak berbakat
1,perempuan,1,1,0,0,tidak berbakat
104,perempuan,1,1,0,0,tidak berbakat
42,laki-laki,1,1,1,1,berbakat
41,laki-laki,1,0,0,0,tidak berbakat
4,laki-laki,1,1,1,1,berbakat
15,laki-laki,0,1,0,0,tidak berbakat
17,laki-laki,1,1,0,0,tidak berbakat
52,perempuan,1,1,0,0,tidak berbakat
40,laki-laki,0,0,0,0,tidak berbakat
38,laki-laki,0,0,0,0,tidak berbakat
5,laki-laki,1,1,0,0,tidak berbakat
53,perempuan,1,1,1,1,berbakat
106,perempuan,0,0,0,0,tidak berbakat
108,laki-laki,1,1,1,1,berbakat
0,laki-laki,0,0,0,0,tidak berbakat
34,perempuan,1,1,0,0,tidak berbakat
28,perempuan,1,1,1,1,berbakat
55,perempuan,1,0,0,0,tidak berbakat
35,perempuan,1,0,1,1,berbakat
23,perempuan,1,1,1,1,berbakat
31,laki-laki,1,1,0,0,tidak berbakat
75,perempuan,1,1,1,1,berbakat
57,perempuan,0,0,0,0,tidak berbakat
89,laki-laki,1,1,0,0,tidak berbakat
99,perempuan,1,1,0,0,tidak berbakat
32,laki-laki,1,1,1,1,berbakat
98,laki-laki,1,1,1,1,berbakat
14,laki-laki,0,1,0,0,tidak berbakat
85,perempuan,0,0,0,0,tidak berbakat
19,perempuan,1,1,1,1,berbakat
29,laki-laki,1,0,1,1,berbakat
49,laki-laki,0,0,0,0,tidak berbakat
82,perempuan,1,1,1,1,berbakat
113,laki-laki,1,1,0,0,tidak berbakat
114,laki-laki,1,0,1,1,berbakat
79,perempuan,1,1,0,0,tidak berbakat
69,laki-laki,1,1,1,1,berbakat
80,perempuan,1,0,1,1,berbakat
20,perempuan,1,1,1,1,berbakat
109,perempuan,0,0,0,0,tidak berbakat
72,laki-laki,0,0,0,0,tidak berbakat
77,laki-laki,1,1,0,0,tidak berbakat
25,perempuan,1,1,1,1,berbakat
37,perempuan,1,0,0,0,tidak berbakat
81,laki-laki,1,1,1,1,berbakat
102,laki-laki,1,1,0,0,tidak berbakat
46,perempuan,1,1,0,0,tidak berbakat
105,perempuan,0,0,0,0,tidak berbakat
39,laki-laki,1,1,0,0,tidak berbakat
65,laki-laki,1,1,1,1,berbakat
58,perempuan,1,1,1,1,berbakat
12,laki-laki,0,0,0,0,tidak berbakat
110,perempuan,0,0,0,0,tidak berbakat
88,laki-laki,0,0,0,0,tidak berbakat
70,perempuan,0,1,0,0,tidak berbakat
87,perempuan,0,0,0,0,tidak berbakat
36,perempuan,0,1,0,0,tidak berbakat
21,laki-laki,0,1,1,1,berbakat
83,laki-laki,1,1,1,1,berbakat
9,perempuan,1,0,1,1,berbakat
103,laki-laki,1,1,0,0,tidak berbakat
112,perempuan,1,1,1,1,berbakat
67,laki-laki,1,1,0,0,tidak berbakat
64,laki-laki,1,1,1,1,berbakat
47,perempuan,1,1,1,1,berbakat
44,laki-laki,1,1,1,1,berbakat

In [36]:
x_train_y_train

,jenis_kelamin,tinggi_badan,berat_badan,kemampuan_fisik,teknik_dasar,hasil_bakat
54,0,1,0,1,1,1
115,1,1,1,1,1,1
95,0,1,1,1,1,1
101,0,0,0,0,0,0
96,1,0,1,1,1,1
91,0,1,1,0,0,0
63,0,1,1,0,0,0
27,1,1,1,1,1,1
18,0,1,1,1,1,1
11,1,1,0,0,0,0
59,1,1,1,0,0,0
68,0,1,1,1,1,1
61,1,1,0,0,0,0
76,0,1,1,0,0,0
50,1,0,1,0,0,0
1,0,1,1,0,0,0
104,0,1,1,0,0,0
42,1,1,1,1,1,1
41,1,1,0,0,0,0
4,1,1,1,1,1,1
15,1,0,1,0,0,0
17,1,1,1,0,0,0
52,0,1,1,0,0,0
40,1,0,0,0,0,0
38,1,0,0,0,0,0
5,1,1,1,0,0,0
53,0,1,1,1,1,1
106,0,0,0,0,0,0
108,1,1,1,1,1,1
0,1,0,0,0,0,0
34,0,1,1,0,0,0
28,0,1,1,1,1,1
55,0,1,0,0,0,0
35,0,1,0,1,1,1
23,0,1,1,1,1,1
31,1,1,1,0,0,0
75,0,1,1,1,1,1
57,0,0,0,0,0,0
89,1,1,1,0,0,0
99,0,1,1,0,0,0
32,1,1,1,1,1,1
98,1,1,1,1,1,1
14,1,0,1,0,0,0
85,0,0,0,0,0,0
19,0,1,1,1,1,1
29,1,1,0,1,1,1
49,1,0,0,0,0,0
82,0,1,1,1,1,1
113,1,1,1,0,0,0
114,1,1,0,1,1,1
79,0,1,1,0,0,0
69,1,1,1,1,1,1
80,0,1,0,1,1,1
20,0,1,1,1,1,1
109,0,0,0,0,0,0
72,1,0,0,0,0,0
77,1,1,1,0,0,0
25,0,1,1,1,1,1
37,0,1,0,0,0,0
81,1,1,1,1,1,1
102,1,1,1,0,0,0
46,0,1,1,0,0,0
105,0,0,0,0,0,0
39,1,1,1,0,0,0
65,1,1,1,1,1,1
58,0,1,1,1,1,1
12,1,0,0,0,0,0
110,0,0,0,0,0,0
88,1,0,0,0,0,0
70,0,0,1,0,0,0
87,0,0,0,0,0,0
36,0,0,1,0,0,0
21,1,0,1,1,1,1
83,1,1,1,1,1,1
9,0,1,0,1,1,1
103,1,1,1,0,0,0
112,0,1,1,1,1,1
67,1,1,1,0,0,0
64,1,1,1,1,1,1
47,0,1,1,1,1,1
44,1,1,1,1,1,1

request file inputan

In [ ]:
nama = 'laode azhar'
jenis_kelamin = 'laki - laki'
tinggi_badan = ''
berat_badan = ''
kemampuan_fisik
teknik_dasar

In [72]:
data1 = test.drop(labels='hasil_bakat', axis=1)
data1 =  data1.drop(labels='jenis_kelamin', axis=1)
data1['jenis_kelamin'] = 0

In [74]:
data1.astype('int')

   tinggi_badan  berat_badan  kemampuan_fisik  teknik_dasar  jenis_kelamin
0             0            0                0             0              0

In [39]:
y_train.shape

(81,)

In [40]:
x_train.shape

(81, 5)

In [41]:
model = GaussianNB()
model.fit(x_train, y_train)

GaussianNB()

In [63]:
model.predict(data1)

array([0], dtype=int64)